/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnic */

#ifndef _Included_jnic
#define _Included_jnic
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnic
 * Method:    jcalepochc
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_jnic_jcalepochc
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
