#
# Makefile For LST and the Source RA-DEC Precession, Equitorial to Horizontal Coordinate system conversion
# , Rise & Set time calculution - Jitendra Dec 2nd, 2010
#
.SUFFIXES:
.SUFFIXES:	.c .f .o

CC=cc
F77=gf4
OPT=-c ${DEBUG}
LINK= ${F77}

HEADERS		= source.h constant.h
INCLUDEDIR=
LIBPATH=
LIBS=-lm
# ASSIGN SLALIB PATH TO LOCALLY INSTALLED FORTRAN libsla.a 
SLALIB=/usr/local/lib/libsla.a   
JNIPATH=-shared -I/usr/lib/jvm/java-6-sun/include -I//usr/lib/jvm/java-6-sun/include/linux/ 

#azel.f rset.f

CFILES0		= calepochc.c precess.c rset.c azel.c stime_.c ltostr.c fangle_.c sangle_.c  
FFILES0		= fryej.f ep2daj.f crdprec.f crdrd2ae.f slagmst_.f slacaldj.f slacldj.f sladranrm.f djm2e.f \
slapreces.f sladjcl.f sladmxv.f slaprec.f sladcc2s.f sladcs2c.f slaprebn.f map.f


COBJECT		= ${CFILES0:.c=.o}
FOBJECT		= ${FFILES0:.f=.o}

TARGET=	 libcalepochc.so

#all: ${HEADERS} ${TARGET} change before mod march 21,2011

.c.o:
	${CC} ${OPT} -o ${<:.c=.o} $<

.f.o: 
	${F77} ${OPT} -o ${<:.f=.o} $<

#calepochc : ${HEADER} ${COBJECT} ${FOBJECT}  change before mod march 21,2011
#	${LINK} ${COBJECT} ${FOBJECT} ${SLALIB} -o $@

${TARGET} : ${HEADER} ${COBJECT} ${FOBJECT} 
	${CC} ${COBJECT} ${FOBJECT} ${SLALIB} ${JNIPATH} -o $@


clean :
	/bin/rm -rf *.o core
